version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket lambda-bucket-code-pipeline --output-template-file outputSamTemplate.yml
artifacts:
  files:
    - samTemplate.yml
    - outputSamTemplate.yml
